{% set name = "cysignals" %}
{% set version = "1.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/cysignals/archive/{{ version }}.tar.gz
  sha256: 1370622692f1bc159c6524395e9cf2f5fe16b49ee437a9bb96d6a8689e2d4b2b
  patches:
    - qemu.patch
    # See https://github.com/conda-forge/cysignals-feedstock/issues/37
    - issue-159.patch  # [aarch64]

build:
  number: 1
  script:
    - export CPPFLAGS=${CPPFLAGS/-D_FORTIFY_SOURCE=2/}   # [unix]
    - {{ PYTHON }} -m pip install . -vv -Csetup-args=${MESON_ARGS// / -Csetup-args=}  # [unix]
    - {{ PYTHON }} -m pip install . -vv      # [not unix]
    - pytest src                             # [build_platform == target_platform]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.28                          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - python
    - meson-python
    - cython >=0.28
    - pip
    - pytest
  run:
    - python

test:
  imports:
    - cysignals

about:
  home: https://github.com/sagemath/cysignals
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: interrupt and signal handling for Cython

  doc_url: http://cysignals.readthedocs.io
  dev_url: https://github.com/sagemath/cysignals

extra:
  recipe-maintainers:
    - dfroger
    - isuruf
    - saraedum
