{% set name = "cysignals" %}
{% set version = "1.7.0" %}
{% set sha256 = "69c84c7b2a93c5e29e069c2c521f05b148010aeaf470037b73e0aabdeabe4070" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - cython
    - pip
    - toolchain
    - pari
  run:
    - python
    - pari

test:
  imports:
    - cysignals

about:
  home: https://github.com/sagemath/cysignals
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'interrupt and signal handling for Cython'

  doc_url: http://cysignals.readthedocs.io
  dev_url: https://github.com/sagemath/cysignals

extra:
  recipe-maintainers:
    - dfroger
    - isuruf
    - saraedum
