{% set name = "cysignals" %}
{% set version = "1.8.1" %}
{% set sha256 = "fd07c48d9983e214fc95862e19d0f67190df83e15eec938242cfc0d77366d3c2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - upstream_issue88_anonymous.patch
    - fix_tests.diff   # [py==37]

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cython
    - pip
    - pari
  run:
    - python
    - pari

test:
  imports:
    - cysignals

about:
  home: https://github.com/sagemath/cysignals
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'interrupt and signal handling for Cython'

  doc_url: http://cysignals.readthedocs.io
  dev_url: https://github.com/sagemath/cysignals

extra:
  recipe-maintainers:
    - dfroger
    - isuruf
    - saraedum
