{% set name = "cysignals" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/cysignals/archive/{{ version }}.tar.gz
  sha256: baaa74f4767573554d78ae804f104d81306d80b939ae182f66492ceebaa58115
  patches:
    - cross.patch  # [build_platform != target_platform]
    - qemu.patch
    # setrlimit calls do not seem to work.
    # Introduced in https://github.com/conda-forge/cysignals-feedstock/pull/27
    # but it is unclear why/whether this change is necessary.
    - remove-setrlimit-on-macOS.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
  host:
    - python
    - setuptools
    - cython
    - pip
    - pari
  run:
    - python
    - pari

test:
  imports:
    - cysignals

about:
  home: https://github.com/sagemath/cysignals
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: interrupt and signal handling for Cython

  doc_url: http://cysignals.readthedocs.io
  dev_url: https://github.com/sagemath/cysignals

extra:
  recipe-maintainers:
    - dfroger
    - isuruf
    - saraedum
