{% set name = "cysignals" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/cysignals/archive/{{ version }}.tar.gz
  sha256: 78273a16d200d3edd2d80fef96a32dab89e9f4105f3e26b3933f4ecf33e1234e
  patches:
    - cross.patch  # [build_platform != target_platform]
    - qemu.patch
    - verbose.patch
    # See https://github.com/conda-forge/cysignals-feedstock/issues/37
    - issue-159.patch  # [aarch64]

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
  host:
    - python
    - setuptools
    - cython <3
    - pip
    - pari
  run:
    - python
    - pari

test:
  imports:
    - cysignals

about:
  home: https://github.com/sagemath/cysignals
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: interrupt and signal handling for Cython

  doc_url: http://cysignals.readthedocs.io
  dev_url: https://github.com/sagemath/cysignals

extra:
  recipe-maintainers:
    - dfroger
    - isuruf
    - saraedum
