appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: HuDPhlIgZ09He0gKat9HEm2EB4Q5OpZtzBRHgP3bqHVWb/8ne2Tok1uCbKHhYVyx5EL0tzIjtF0WHMwVROyxOw/nco+w9boEErfMMOzItLtr8BhWTmjFOmwoJ1W0DUO/9UoE8dX8diOw58YEjyAcqGGyxGL8AyKKh843Lt5XJukHyVI8n14Uw3gHRLBWBebbg/9QpRy8/IyqYwxcRRE+fS+ImgASnRoYdZ8Qu2U2+oS+7ffwfMlPn7dxUcwgyxzJqpxULEPMC8g4+kq84kg/KJqzWRXsD+hwD1wElmgkKOQuj5OjjGaLEb718tteMrBYAH1Dz9Q0CcCw+XN7S5pJ9LLh+Fnwbq9Uy30I/x5I0zmpLITD+67tTN8CQuHqIyEVfT6PTjJzJQdHe7DuSH4bZtvi2/qFoAp1JqwQs0IreJgshkKWTdkJM25EXgkx1tXxQXo0KahCePtym6a6ttbzWFU2Gr3dC67qLZx4G/J69x5JI3kNb2VYbz6/8F58c0zOT/KJJrxbbOlKW5lYVH/eJOzyOCrnnq2rZYVlNa/baLpYFPiSnlDXNIaPyNlCOqHV93uGxUk0yHmoIKpSEUFy1zc0j7PSlvppKNYCgnt4mNnhJY0bTeDs24KQPvOQ8q8M5rtFGD6iIQoWkc4aW8QUrJrnqJnKK0oIY7ZYCoKmToM=}
